import { NextRequest, NextResponse } from 'next/server'
import { getCPClient } from '@/lib/cp-db'

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: campaignId } = await params
    const client = getCPClient()
    const url = new URL(req.url)
    const format = url.searchParams.get('format') || 'csv'

    // Fetch campaign data
    const { data: campaign } = await client
      .from('cp_campaigns')
      .select('*')
      .eq('id', campaignId)
      .single()

    if (!campaign) {
      return NextResponse.json({ error: 'Campaign not found' }, { status: 404 })
    }

    // Fetch creators
    const { data: creators } = await client
      .from('cp_creators')
      .select('*')
      .eq('campaign_id', campaignId)

    // Fetch deliverables
    const { data: deliverables } = await client
      .from('cp_deliverables')
      .select('*, creator:cp_creators(channel_name, platform)')
      .eq('campaign_id', campaignId)

    const totalViews = (deliverables || []).reduce((s, d) => s + (d.views || 0), 0)
    const totalLikes = (deliverables || []).reduce((s, d) => s + (d.likes || 0), 0)
    const totalComments = (deliverables || []).reduce((s, d) => s + (d.comments || 0), 0)
    const totalSpend = (creators || []).reduce((s, c) => s + (c.quoted_cost || 0), 0)
    const totalInternal = (creators || []).reduce((s, c) => s + (c.internal_cost || 0), 0)
    const avgEng = (deliverables || []).length > 0
      ? (deliverables || []).reduce((s, d) => s + (d.engagement_rate || 0), 0) / (deliverables || []).length
      : 0

    if (format === 'pdf') {
      // Generate HTML-based PDF content
      const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${campaign.name} - Report</title>
<style>
body{font-family:Arial,sans-serif;padding:40px;color:#1a1a2e}
h1{color:#0052CC;border-bottom:2px solid #0052CC;padding-bottom:8px}
h2{color:#333;margin-top:24px}
table{width:100%;border-collapse:collapse;margin:16px 0}
th,td{border:1px solid #ddd;padding:10px;text-align:left;font-size:13px}
th{background:#f5f5f5;font-weight:700}
.kpi{display:inline-block;margin:8px 16px 8px 0}
.kpi-value{font-size:24px;font-weight:800;color:#0052CC}
.kpi-label{font-size:11px;color:#666;text-transform:uppercase}
</style></head><body>
<h1>${campaign.name}</h1>
<p>Brand: ${campaign.brand} | Status: ${campaign.status}</p>
<div class="kpi"><div class="kpi-value">${totalViews.toLocaleString()}</div><div class="kpi-label">Total Views</div></div>
<div class="kpi"><div class="kpi-value">${totalLikes.toLocaleString()}</div><div class="kpi-label">Total Likes</div></div>
<div class="kpi"><div class="kpi-value">${totalComments.toLocaleString()}</div><div class="kpi-label">Comments</div></div>
<div class="kpi"><div class="kpi-value">${avgEng.toFixed(2)}%</div><div class="kpi-label">Avg Engagement</div></div>
<div class="kpi"><div class="kpi-value">₹${totalSpend.toLocaleString()}</div><div class="kpi-label">Total Spend</div></div>
<div class="kpi"><div class="kpi-value">₹${totalInternal.toLocaleString()}</div><div class="kpi-label">Internal Cost</div></div>
<div class="kpi"><div class="kpi-value">₹${(totalSpend - totalInternal).toLocaleString()}</div><div class="kpi-label">Margin</div></div>
<h2>Creator Performance</h2>
<table><thead><tr><th>Creator</th><th>Platform</th><th>Views</th><th>Likes</th><th>Comments</th><th>Engagement</th><th>Cost</th></tr></thead>
<tbody>${(creators || []).map(c => {
  const d = (deliverables || []).find(del => del.creator?.channel_name === c.channel_name)
  return `<tr><td>${c.channel_name}</td><td>${c.platform}</td><td>${(d?.views || 0).toLocaleString()}</td><td>${(d?.likes || 0).toLocaleString()}</td><td>${(d?.comments || 0).toLocaleString()}</td><td>${(d?.engagement_rate || 0).toFixed(2)}%</td><td>₹${(c.quoted_cost || 0).toLocaleString()}</td></tr>`
}).join('')}</tbody></table>
<p style="margin-top:32px;font-size:11px;color:#999">Generated by TheBoredMonkey Campaign Panel</p>
</body></html>`

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="${campaign.name}-report.html"`,
        },
      })
    }

    // CSV format (default)
    const headers = ['Creator', 'Platform', 'Views', 'Likes', 'Comments', 'Engagement Rate', 'Quoted Cost', 'Internal Cost']
    const rows = (creators || []).map(c => {
      const d = (deliverables || []).find(del => del.creator?.channel_name === c.channel_name)
      return [
        c.channel_name, c.platform, d?.views || 0, d?.likes || 0, d?.comments || 0,
        `${(d?.engagement_rate || 0).toFixed(2)}%`, c.quoted_cost || 0, c.internal_cost || 0,
      ]
    })

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')

    return new NextResponse(csv, {
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': `attachment; filename="${campaign.name}-report.csv"`,
      },
    })
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
